POST http://14.5.86.192:8090/api/signup
Content-Type: application/json

{
  "userId" : "wondo8449",
  "password" : "dgf9tmASD@",
  "userName" : "김예찬3",
  "phone" : "01099408245",
  "birthday" : "1997-01-27",
  "address": "효자동",
  "baptismStatus": "세례",
  "job": "개발자",
  "school": "남서울대",
  "tree": "오예나무"
}

###
POST http://14.5.86.192:8090/api/login
Content-Type: application/json

{
  "userId": "wondo8449",
  "password": "dgf9tmASD@"
}

###
POST http://14.5.86.192:8090/api/sendSMS
Content-Type: application/json

{
  "phone": "01099408245"
}
